waypoints:
  - {x: 5.81, y: 2.01, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.82, y: 2.12, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 12.84, y: 2.38, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.94, y: -0.84, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.94, y: -0.84, z: 1.0, yaw: -1.57, flag: 1}
  - {x: 11.94, y: -0.84, z: 1.0, yaw: -1.2, flag: 1}
  - {x: 13.27, y: 2.26, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 16.24, y: -0.26, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.72, y: 2.86, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 18.36, y: 5.67, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 19.18, y: 9.04, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 18.01, y: 9.18, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 15.31, y: 8.95, z: 1.0, yaw: 0.0, flag: 0}
  #- {x: 8.27, y: 8.2, z: 1.0, yaw: 0.0, flag: 0}
  #- {x: 7.33, y: 3.83, z: 1.0, yaw: 0.0, flag: 0}
  #- {x: 7.33, y: 1.88, z: 1.0, yaw: 0.0, flag: 0}
  #- {x: 0.0, y: 0.0, z: 1.0, yaw: 0.0, flag: 0}
 




