waypoints:
  - {x: 5.88, y: 1.87, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 8.87, y: 1.96, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 13.46, y: 2.13, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.89, y: -0.95, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.89, y: -0.95, z: 1.2, yaw: -1.57, flag: 1}
  - {x: 12.89, y: -0.95, z: 1.2, yaw: -1.2, flag: 1}
  - {x: 14.43, y: 2.31, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 17.29, y: 0.26, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 16.05, y: 4.32, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 14.30, y: 9.19, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.17, y: 9.64, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.33, y: 9.09, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 8.86, y: 5.53, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 8.88, y: 2.79, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 0.0, y: 0.0, z: 1.2, yaw: 0.0, flag: 0}

 




