waypoints:
  - {x: 5.23, y: 1.85, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.47, y: 1.88, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 12.30, y: 1.80, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.87, y: -0.91, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.87, y: -0.91, z: 1.0, yaw: -1.57, flag: 1}
  - {x: 11.87, y: -0.91, z: 1.0, yaw: -1.2, flag: 1}
  - {x: 12.43, y: 2.0, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 15.58, y: 0.22, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 16.94, y: 2.82, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.67, y: 5.97, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.20, y: 8.38, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 10.07, y: 8.28, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.27, y: 8.2, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 7.33, y: 3.83, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 7.33, y: 1.88, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 0.0, y: 0.0, z: 1.0, yaw: 0.0, flag: 0}
 




