waypoints:
  - {x: 6.10, y: 1.90, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.15, y: 2.07, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 13.60, y: 2.09, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 16.37, y: 0.45, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 15.9, y: 3.69, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 14.83, y: 6.49, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.37, y: 9.27, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.32, y: 8.92, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.32, y: 8.92, z: 1.2, yaw: 1.57, flag: 1}
  - {x: 9.32, y: 8.92, z: 1.2, yaw: 0.8, flag: 1}
  - {x: 11.95, y: 9.41, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.52, y: 6.88, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 13.15, y: 2.29, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.82, y: -1.22, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.82, y: -1.22, z: 1.2, yaw: -1.57, flag: 1}
  - {x: 12.82, y: -1.22, z: 1.2, yaw: -1.2, flag: 1}
  - {x: 13.40, y: 2.15, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 10.83, y: 2.26, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 8.96, y: 2.26, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 0.0, y: 0.0, z: 1.2, yaw: 0.0, flag: 0}


 




