waypoints:
  - {x: 6.10, y: 1.90, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.15, y: 2.07, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.98, y: 2.00, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 13.09, y: -1.22, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 13.09, y: -1.22, z: 1.2, yaw: -1.57, flag: 1}
  - {x: 13.09, y: -1.22, z: 1.2, yaw: -1.2, flag: 1}
  - {x: 13.80, y: 1.85, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 16.55, y: 0.45, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 15.86, y: 3.79, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 14.20, y: 6.53, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.44, y: 9.3, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.64, y: 9.6, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.12, y: 8.83, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 9.12, y: 8.83, z: 1.2, yaw: 1.57, flag: 1}
  - {x: 9.12, y: 8.83, z: 1.2, yaw: 0.8, flag: 1}
  - {x: 11.96, y: 9.68, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 14.86, y: 6.53, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 16.00, y: 2.12, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 12.50, y: 1.82, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 8.7, y: 1.82, z: 1.2, yaw: 0.0, flag: 0}
  - {x: 0.0, y: 0.0, z: 1.2, yaw: 0.0, flag: 0}

 




