waypoints:
  - {x: 5.23, y: 1.85, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.47, y: 1.88, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 12.30, y: 1.80, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.87, y: -0.91, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.87, y: -0.91, z: 1.2, yaw: -1.57, flag: 1}
  - {x: 11.87, y: -0.91, z: 1.2, yaw: -1.2, flag: 1}
  - {x: 12.48, y: 2.0, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 15.58, y: 0.22, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 16.94, y: 2.82, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.67, y: 5.97, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.95, y: 8.50, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 17.95, y: 8.50, z: 1.2, yaw: 1.50, flag: 1}
  - {x: 14.89, y: 8.70, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 11.36, y: 9.05, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 9.03, y: 8.94, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.06, y: 5.4, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 8.02, y: 2.23, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 0.0, y: 0.0, z: 1.0, yaw: 0.0, flag: 0}

 




